[workspace]
resolver = "2"
members = [
    "vault-core",
    "vault-api"
]

[workspace.dependencies]
vault-core = { path = "./vault-core" }
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"