[package]
name = "vault-core"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
lto = true
panic = "abort"

[profile.dev]
panic = "abort"

[lib]
name = "vault_core"
crate-type = ["rlib"]

[features]
softhsm = []
lunahsm = []