[package]
name = "vault-api"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }

[features]
softhsm = []
lunahsm = []